# Generated by Django 4.2.7 on 2023-11-26 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='username_carduser', to=settings.AUTH_USER_MODEL), max_length=64)),
                ('profile_image', models.ImageField(default='media/default_profile_image.png', upload_to='profile_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_carduser', to=settings.AUTH_USER_MODEL)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='username_carduser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
